### ISSUE TITLE
Understanding token_secret and token_issuer 

### ISSUE THREAD

**Issue by tgelite** [greenpau/caddy-auth-jwt#43]
Assuming the following configuration present in a Caddyfile, based on examples presented in the caddy-auth-jwt documentation.

```
...
jwt {
      primary yes
      trusted_tokens {
          static_secret {
             token_name access_token
             token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
             token_issuer e1008f2d-ccfa-4e62-bbe6-c202ec2988cc
             token_lifetime 3600
             token_sign_method HS256
            }
        }
      }
...
```

After reading docs, previous issues here in this github, attempting to identify parallel terms in jwt documentation and guides, or looking at online jwt generators; I can not identify a good explanation for token_secret and token_issuer.  So I have a few questions.

1. Should these values be "unique" per deployment.  When I look at it I'm saying 'yes of course', and based on the examples they are. 
2. Are these generated values? They seem to be with the - structure and length of blocks, or are these just arbitrary strings of specific length separated by dashes? 
3. If these should be unique, and should be generated; How do we generate these values in a way that caddy-auth-jwt understands? 

Thanks!

**Comment by jaedle** [comment]
I hope that some help on this is fine for you, @greenpau 😄

[This](https://jwt.io/introduction/) answers a lot of questions on token signatures.
The issuer (not 100% fit, I know) is somehow explained [here](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDTValidation).

Long story short: It could be that an identity provider issues different tokens with the same secret (private key / shared secret), but with different issuers. That's completely valid and the reason you need to check the issuer.

Some overall recommendation from my side:
If you're planning to run something **bigger** on production I would highly recommend using something stronger from a cryptography perspective: Sign your JWT with a RSA-Key (private/public-keypair).

I think it's not too hard to brute-force a shared secret with a few digits length. Going for a RSA-key with 4096 bits may be way harder.

Let's go for you questions:
(1): As this a shared secret (signer and validator needs it), I would highly recommend to make this unique, yes. Anyone who has your secret can generate keys and pretend to be someone else. I put those values to environment variables to let them out of the config of caddy to have them only locally on the machine / container that's running Caddy.
(2): Looks like [uuids](https://en.wikipedia.org/wiki/Universally_unique_identifier) ;)
(3): Just try out what happens. If you understand the HMAC-Signature, you should be able to understand which values are allowed for those kind of inputs.

Some overall recommendation: Spend some time understanding basic security concepts and mechanisms used on the modern web (i.e. OIDC). It's pretty easy to leak very sensitive information if you are unsure about what you're doing.

**Comment by greenpau** [comment]
@jaedle , thank you for background information! 👍 

@tgelite , I will try supplimenting @jaedle  answer.

1. The `token_issuer` directive is unnecessary. I am going to remove it from `portal` and `jwt` plugins next week.

Initially, when creating a plugin, I create the `token_issuer` directive to see "Issuer" on a token. Over time, I understood that its useless ... Instead I started calculating the URL a user hit upon successful authentication and recording it in `iss` automatically.

Additionally, please note that if I was authenticating users using `oauth2`, then I will add the upstream to `origin`.

```json
{
  "iss": "https://localhost:8443/auth/oauth2/okta/authorization-code-callback",
  "origin": "https://dev-124643.okta.com/oauth2/default",
}
```

Importantly, the `iss` is not use in the process of validation of tokens. The most important thing is the length of the secret.

2. The `token_secret` directive was created for the storing of shared "password" to sign/validate tokens.

The reason my secrets look like UUIDs is because I literally generate them with `uuidgen` command. They can be arbitrary length.

In a production deployment, I recommend using private/public key and using `token_rsa_file` directive, instead of `token_secret`.

Please read [here](https://github.com/greenpau/caddy-auth-portal#jwt-tokens), including the instruction how to generate `token_rsa_file`.

Important distinction:
1. `portal` plugin **issues/signs** tokens
2. `jwt` plugin **verifies** tokens

The `jwt` plugin can have multiple trusted tokens configured because it might work with multiple token issuers.

```
  route /prometheus* {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_name usertoken
          token_secret 8a0441ab201e42258b2bcf8bba8f1bf7
        }
        public_key {
          token_name access_token
          token_name usertoken
          token_rsa_file 57f918a756414057b7bfcf32c3419272 /etc/caddy/auth/verify_key.pem
        }
      }
```

---

@tgelite , @jaedle , after reading the above, please ask clarifying questions.

**Comment by tgelite** [comment]
This is all perfect.

Thank you very much for the overview and reference detail. I have not worked with OpenID up to this point so thanks for  the pointer on essential reading @jaedle.  Also, thank you and @greenpau for the insight into the importance of the RSA implementation for production and pointer to its.   I'll look at that next, i'm just setting up a dev environment for now. 

@greenpau - Right on target with the deeper explanation, as well as clarification of your use of uuidgen for the secret.  I understand now from your additional example that the secret can be any string, just make it complex for strength of it. 

I'll continue on setup and testing now understanding what those are!

Have a great day!

**Comment by greenpau** [comment]
@tgelite , @jaedle , as of [v1.3.6](https://github.com/greenpau/caddy-auth-portal/releases/tag/v1.3.6), the `token_issuer` is no longer a part of the `portal` and `jwt` plugins.
